CREATE CONSTRAINT device_id IF NOT EXISTS FOR (d:Device) REQUIRE d.id IS UNIQUE;
CREATE CONSTRAINT device_slug IF NOT EXISTS FOR (d:Device) REQUIRE d.slug IS UNIQUE;
CREATE CONSTRAINT symptom_id IF NOT EXISTS FOR (s:Symptom) REQUIRE s.id IS UNIQUE;
CREATE CONSTRAINT guide_id IF NOT EXISTS FOR (g:RepairGuide) REQUIRE g.id IS UNIQUE;
CREATE CONSTRAINT part_id IF NOT EXISTS FOR (p:Part) REQUIRE p.id IS UNIQUE;
CREATE CONSTRAINT tool_id IF NOT EXISTS FOR (t:Tool) REQUIRE t.id IS UNIQUE;
CREATE CONSTRAINT venue_id IF NOT EXISTS FOR (v:RepairVenue) REQUIRE v.id IS UNIQUE;
CREATE CONSTRAINT city_id IF NOT EXISTS FOR (c:City) REQUIRE c.id IS UNIQUE;
CREATE CONSTRAINT brand_id IF NOT EXISTS FOR (b:Brand) REQUIRE b.id IS UNIQUE;
CREATE CONSTRAINT category_id IF NOT EXISTS FOR (c:Category) REQUIRE c.id IS UNIQUE;
CREATE CONSTRAINT cause_id IF NOT EXISTS FOR (c:Cause) REQUIRE c.id IS UNIQUE;

CREATE INDEX device_name IF NOT EXISTS FOR (d:Device) ON (d.name);
CREATE INDEX symptom_name IF NOT EXISTS FOR (s:Symptom) ON (s.name);
CREATE INDEX guide_name IF NOT EXISTS FOR (g:RepairGuide) ON (g.title);
CREATE INDEX venue_name IF NOT EXISTS FOR (v:RepairVenue) ON (v.name);
